"""
Dual-Head MCM Inference:

  WRITE HEAD — takes raw interaction log → outputs structured memory JSON + graph edges
  READ  HEAD — takes query + graph schema → outputs traversal path to answer

Both heads share the same base model. Each head is a separate LoRA adapter:
  - write_adapter:  fine-tuned on (conversation → memory + edges + retrieval examples)
  - read_adapter:   fine-tuned on (query + graph schema → path + answer) pairs
                     training data is GENERATED by the write head during consolidation
"""

import json
import re
from typing import Any

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer


WRITE_SYSTEM_PROMPT = """You are a memory consolidation model. Given a raw agent interaction log:

1. Extract structured memory units (facts, preferences, task summaries, abstractions, open threads, corrections)
2. Identify relationships between units as graph edges
3. Generate example retrieval queries with their graph traversal paths

Output ONLY valid JSON matching this structure:
{
  "memory": { "facts": [...], "preferences": [...], "task_summaries": [...], "reusable_abstractions": [...], "open_threads": [...], "corrections": [...] },
  "graph_edges": [ {"from_content": "...", "to_content": "...", "relation": "..."} ],
  "retrieval_examples": [ {"query": "...", "path_description": "...", "answer_units": ["..."] } ]
}"""


READ_SYSTEM_PROMPT = """You are a memory retrieval model. Given a user query and a knowledge graph schema, output the optimal traversal path to answer the query.

Output ONLY valid JSON:
{
  "reasoning": "brief chain of thought about which nodes/edges are relevant",
  "path": ["node_id_1", "node_id_2", "node_id_3"],
  "answer_from": ["node_id_2", "node_id_3"],
  "confidence": 0.95
}"""


class MCMInference:
    """
    Dual-head MCM using LoRA adapter swapping on a shared base model.

    Write head: consolidation (raw log → structured memory + graph edges + retrieval training data)
    Read head:  retrieval routing (query + graph schema → traversal path)
    """

    def __init__(
        self,
        base_model: str,
        write_adapter_path: str | None = None,
        read_adapter_path: str | None = None,
    ):
        self.tokenizer = AutoTokenizer.from_pretrained(base_model, trust_remote_code=True)
        self.tokenizer.pad_token = self.tokenizer.eos_token

        self._base_model = AutoModelForCausalLM.from_pretrained(
            base_model,
            torch_dtype=torch.bfloat16,
            device_map="auto",
            trust_remote_code=True,
        )

        # Load LoRA adapters if provided
        self._write_adapter_path = write_adapter_path
        self._read_adapter_path = read_adapter_path

        self._write_model = None
        self._read_model = None

        if write_adapter_path:
            self._write_model = PeftModel.from_pretrained(
                self._base_model, write_adapter_path, adapter_name="write"
            ).eval()

        if read_adapter_path:
            if self._write_model is not None:
                # Add second adapter to the same PEFT model
                self._read_model = self._write_model
                self._read_model.load_adapter(read_adapter_path, adapter_name="read")
            else:
                self._read_model = PeftModel.from_pretrained(
                    self._base_model, read_adapter_path, adapter_name="read"
                ).eval()

        # If no adapters, use base model directly for both
        if self._write_model is None:
            self._write_model = self._base_model.eval()
        if self._read_model is None:
            self._read_model = self._write_model

    # ------------------------------------------------------------------
    # WRITE HEAD: raw log → structured memory + graph edges + retrieval training
    # ------------------------------------------------------------------

    def consolidate(self, interaction_log: str, max_new_tokens: int = 6144) -> dict[str, Any]:
        """
        Write head: transform raw interaction log into:
          - memory_units: structured JSON (same schema as before)
          - graph_edges:  relation triples between units
          - retrieval_examples: (query, path, answer) tuples for read-head training

        Returns parsed dict or empty dict on failure.
        """
        # Activate write adapter if using PEFT
        if isinstance(self._write_model, PeftModel):
            self._write_model.set_adapter("write")

        return self._generate(
            system_prompt=WRITE_SYSTEM_PROMPT,
            user_content=f"Interaction log:\n\n{interaction_log}",
            model=self._write_model,
            max_new_tokens=max_new_tokens,
        )

    # Backward compat alias
    def generate(self, interaction_log: str, max_new_tokens: int = 6144) -> dict:
        return self.consolidate(interaction_log, max_new_tokens)

    # ------------------------------------------------------------------
    # READ HEAD: query + graph schema → traversal path
    # ------------------------------------------------------------------

    @property
    def read_lora_ready(self) -> bool:
        """True if the read LoRA adapter has been loaded."""
        return self._read_adapter_path is not None

    def route_query(self, query: str, graph_schema: str, max_new_tokens: int = 512) -> dict[str, Any]:
        """
        Read head: given a natural language query and a compact graph schema,
        output the optimal traversal path through the knowledge graph.

        Args:
            query:        Natural language question from the user/agent
            graph_schema: Compact text representation of the user's knowledge graph
                          (generated by MemoryGraph.get_schema_text())

        Returns:
            {"reasoning": "...", "path": ["id1", "id2"], "answer_from": ["id2"], "confidence": 0.9}
        """
        # Activate read adapter if using PEFT
        if isinstance(self._read_model, PeftModel) and self._read_adapter_path:
            self._read_model.set_adapter("read")

        user_content = f"Query: {query}\n\nKnowledge Graph:\n{graph_schema}"

        return self._generate(
            system_prompt=READ_SYSTEM_PROMPT,
            user_content=user_content,
            model=self._read_model,
            max_new_tokens=max_new_tokens,
        )

    def route_query_base(self, query: str, graph_schema: str, max_new_tokens: int = 512) -> dict[str, Any]:
        """
        Same as route_query but always uses the base model, bypassing any LoRA adapter.
        Called by GraphRouter for tier-1 (full schema) and tier-2 (filtered schema)
        routing before the read LoRA has been trained.
        """
        user_content = f"Query: {query}\n\nKnowledge Graph:\n{graph_schema}"
        return self._generate(
            system_prompt=READ_SYSTEM_PROMPT,
            user_content=user_content,
            model=self._base_model,
            max_new_tokens=max_new_tokens,
        )

    # ------------------------------------------------------------------
    # Shared generation logic
    # ------------------------------------------------------------------

    def _generate(
        self,
        system_prompt: str,
        user_content: str,
        model: Any,
        max_new_tokens: int,
    ) -> dict:
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ]

        inputs = self.tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=True,
            return_tensors="pt",
        )
        # Newer transformers returns BatchEncoding; older returns a raw tensor
        if hasattr(inputs, "input_ids"):
            input_ids = inputs["input_ids"].to(model.device)
        else:
            input_ids = inputs.to(model.device)

        with torch.no_grad():
            output_ids = model.generate(
                input_ids,
                max_new_tokens=max_new_tokens,
                do_sample=False,
                temperature=1.0,
                pad_token_id=self.tokenizer.eos_token_id,
            )

        generated = output_ids[0][input_ids.shape[1]:]
        raw_output = self.tokenizer.decode(generated, skip_special_tokens=True).strip()

        # Debug: print first 300 chars of raw output to diagnose JSON failures
        import os
        if os.environ.get("MCM_DEBUG"):
            print(f"[MCM_DEBUG] raw_output[:300]: {raw_output[:300]!r}")

        # Try strict parse first
        try:
            return json.loads(raw_output)
        except json.JSONDecodeError:
            pass

        # LLM output is often truncated mid-JSON — use json-repair to recover it
        try:
            from json_repair import repair_json
            repaired = repair_json(raw_output, return_objects=True)
            if isinstance(repaired, dict) and repaired:
                return repaired
        except ImportError:
            pass

        # Last resort: find largest valid JSON object substring
        start = raw_output.find("{")
        end = raw_output.rfind("}")
        if start != -1 and end != -1 and end > start:
            try:
                return json.loads(raw_output[start:end + 1])
            except json.JSONDecodeError:
                pass

        if os.environ.get("MCM_DEBUG"):
            print(f"[MCM_DEBUG] JSON parse failed entirely, output length={len(raw_output)}")
        return {}
