"""
Dual-head QLoRA fine-tuning for MCM.

Two separate LoRA adapters on the same base model:
  1. Write adapter: (conversation log → memory JSON + graph edges + retrieval examples)
  2. Read adapter:  (query + graph schema → traversal path + answer nodes)

The write adapter is trained first on synthetic data.
The read adapter is trained later on data GENERATED by the write adapter + knowledge graph.

Usage:
    # Train write head
    python scripts/train_mcm.py --head write --data_dir data/synthetic --output_dir checkpoints/mcm-write-v1

    # Train read head (after accumulating retrieval training data)
    python scripts/train_mcm.py --head read --data_dir data/read_training --output_dir checkpoints/mcm-read-v1
"""

import argparse
from pathlib import Path

from datasets import load_dataset
from peft import LoraConfig, TaskType, get_peft_model, prepare_model_for_kbit_training
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from trl import SFTTrainer

import torch


def load_model_and_tokenizer(model_name: str):
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )
    model = prepare_model_for_kbit_training(model)
    return model, tokenizer


def build_peft_model(model):
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=16,
        lora_alpha=32,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        bias="none",
    )
    return get_peft_model(model, lora_config)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--head", type=str, choices=["write", "read"], default="write",
                        help="Which head to train: 'write' for consolidation, 'read' for retrieval routing")
    parser.add_argument("--base_model", type=str, default="Qwen/Qwen2.5-1.5B-Instruct")
    parser.add_argument("--data_dir", type=str, default="data/synthetic")
    parser.add_argument("--output_dir", type=str, default="checkpoints/mcm-write-v1")
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--lr", type=float, default=2e-4)
    parser.add_argument("--per_device_batch_size", type=int, default=4)
    parser.add_argument("--grad_accumulation_steps", type=int, default=8)
    parser.add_argument("--max_seq_length", type=int, default=4096)
    args = parser.parse_args()

    # Read head uses shorter sequences (query + graph schema, not full logs)
    if args.head == "read":
        args.max_seq_length = min(args.max_seq_length, 2048)

    # Load data
    data_dir = Path(args.data_dir)
    dataset = load_dataset(
        "json",
        data_files={
            "train": str(data_dir / "train.jsonl"),
            "validation": str(data_dir / "val.jsonl"),
        },
    )

    # Load model
    print(f"Loading {args.base_model}...")
    model, tokenizer = load_model_and_tokenizer(args.base_model)
    model = build_peft_model(model)
    model.print_trainable_parameters()

    # Training args
    training_args = TrainingArguments(
        output_dir=args.output_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.per_device_batch_size,
        gradient_accumulation_steps=args.grad_accumulation_steps,
        learning_rate=args.lr,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,
        bf16=True,
        logging_steps=10,
        evaluation_strategy="steps",
        eval_steps=100,
        save_strategy="steps",
        save_steps=200,
        save_total_limit=3,
        load_best_model_at_end=True,
        report_to="wandb",
        run_name=f"mcm-{args.head}-v1",
    )

    # Train
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset["train"],
        eval_dataset=dataset["validation"],
        args=training_args,
        max_seq_length=args.max_seq_length,
    )

    print("Starting training...")
    trainer.train()
    trainer.save_model(args.output_dir)
    print(f"Model saved to {args.output_dir}")


if __name__ == "__main__":
    main()
